### Register Admin
curl --location --request POST 'http://localhost:6969/api/admin/auth/register' \
--header 'Content-Type: application/json' \
--data-raw '{
  "email": "test@example.com",
  "password": "StrongPassword123"
}'

### Login Admin
curl --location --request POST 'http://localhost:6969/api/admin/auth/login' \
--header 'Content-Type: application/json' \
--data-raw '{
  "email": "test@example.com",
  "password": "StrongPassword123"
}'

