### Get all users
GET http://localhost:6969/api/admin/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NGIyZDhhZjQzY2Y3OWZiOTY0NzA4MyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0OTc1ODMyNSwiZXhwIjoxNzQ5ODQ0NzI1fQ.gl4AFDrjv2NEHEbe1RrsIOwUcw8rLvi6I3M3n7Co7BU
Content-Type: application/json


### Export users to CSV
POST http://localhost:6969/api/admin/users/export
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "filters": {
    "email": "admin@example.com"
  }
}


### Block a user by ID
POST http://localhost:6969/api/admin/users/USER_ID_HERE/block
Authorization: Bearer {{auth_token}}
Content-Type: application/json


### Delete a user by ID
DELETE http://localhost:6969/api/admin/users/USER_ID_HERE
Authorization: Bearer {{auth_token}}
Content-Type: application/json
